package com.stubhub.domain.account.common.enums;

public enum ErrorCode {
	COMMUNICATION_ERROR,INVALID_SELLER,SYSTEM_ERROR,INVALID_INPUT,SELLER_NOT_AUTHORIZED, INVALID_LISTINGID, USER_NOT_AUTHORIZED, MAX_LENGTH_EXCEEDED, INVALID_EVENT_ID, MISSING_EVENT_ID, USER_NOT_FOUND,INVALID_BUYER
}
