package com.stubhub.domain.account.common.enums;

public enum SortColumnType {
	EVENT_DATE_LOCAL,
	EVENT_DESCRIPTION,
	SECTION,
	QUANTITY,
	QUANTITY_REMAIN,
	TICKET_PRICE,
	EXPECTED_INHAND_DATE,
	TICKET_SYSTEM_STATUS,
	TICKET_MEDIUM,
	SALE_END_DATE,
	SOLD_DATE,
	SALE_CATEGORY,
	INHAND_DATE,
	PRICE_PER_TICKET,
	ORDER_PROC_STATUS_ID,
	SOLD_QUANTITY,
	TICKET_MEDIUM_ID,
	COST_PER_TICKET,
    SELLER_PAYOUT_AMOUNT, ROW_DESC
}
